name: dolomiti-vector-search
services:
  postgresml:
    image: ghcr.io/postgresml/postgresml:2.9.3
    tty: true
    stdin_open: true
    ports:
      - "5433:5432"
      - "8000:8000"
    volumes:
      - postgresml_data:/var/lib/postgresql
    command: sudo -u postgresml psql -d postgresml

volumes:
  postgresml_data: